### ISSUE TITLE
`ReplaceEmoticons` overly broad

### ISSUE THREAD

**Issue by askvortsov1** [justoverclockl/flarum-ext-emoticonpack#1]
https://github.com/justoverclockl/flarum-ext-emoticonpack/blob/main/js/src/forum/ReplaceEmoticons.js#L129 replaces all <p> elements across the entire page. This can be problematic, because it affects elements outside of the comment. In particular, this throws off the rich text editor's cursor.

Consider using `this.element.querySelectorAll` instead.

**Comment by justoverclockl** [comment]
thanks for this issue, i will try your solutions

**Comment by justoverclockl** [comment]
Done!
