### ISSUE TITLE
replacing innerHTML within onupdate event is not a good idea

### ISSUE THREAD

**Issue by n0099** [justoverclockl/flarum-ext-emoticonpack#2]
https://github.com/justoverclockl/flarum-ext-emoticonpack/blob/a5faeffc405b5410bc78b240d90cf6719586ff52/js/src/forum/ReplaceEmoticons.js#L129
This will replace the entire child nodes under `div.Post-body`, for replacing `:emoji:` with images.

But all the nodes will not be reused after the replace, so the browser will have to parse html string and render them again, it's a unnecessary performance overhead.

And it would be a problem when post body have embed external resource such as `<iframe src="//www.youtube.com/embed/" />`, the iframe will get reloaded after other unrelated dom updates (including click other popups, scroll to load more posts), since they triggered the `onupdate` event and `ReplaceEmoticons`.

related: https://discuss.flarum.org/d/27688-oncreate-onupdate-method-doesnt-work-as-expected

I think for this extension, we should finish emoji code transform in backend using s9e\TextFormatter: https://docs.flarum.org/extend/formatting and https://s9etextformatter.readthedocs.io/Plugins/Emoticons/Add_emoticons/, like what the flarum/emoji extension did in https://github.com/flarum/emoji/blob/8dc75db46a2d0a288a737187dedc48faca9704f8/extend.php#L18-L29

**Comment by justoverclockl** [comment]
i'm open to PR if you have another solution ;)
